- name: Add Repository Signing Key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: Add a Source List File
  apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main
    state:  present
    update_cache: yes

- name: Install RabbitMQ Package
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes
  notify: Start service